- hosts: ipmi_hosts
  gather_facts: false
  vars:
    power_action: powerstatus
  tasks:
    - delegate_to: "{{ ipmi_host }}"
      raw: >-
        racadm serveraction {{ power_action }}
      register: res
      failed_when: >-
        "error" in res.stdout.lower()

    - debug:
        var: res.stdout
