- hosts: ipmi_hosts
  gather_facts: false
  vars:
    default_password: calvin
  tasks:
    - delegate_to: "{{ ipmi_host }}"
      raw: >-
        racadm config -g cfgUserAdmin -o cfgUserAdminPassword -i 2 "{{ ipmi_password }}"
      register: res

    - debug:
        var: res.stdout_lines
